### ISSUE TITLE
Correct dataset for AGL sounds?

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#106]
Right now the spreadsheet linked is this one, which has "old" in its name:
https://docs.google.com/spreadsheets/d/1sbeoPlEKxyjzlmWgzeSCVrumoS0wlMpX_Puv074r9lM/edit#gid=1664900378

Should it be replaced by this one?
https://docs.google.com/spreadsheets/d/1yCKAsu-vvQGemPga22F1cdtn90gs7Vp8UCto7HH10cE/edit#gid=818895612

cc @alecristia

**Comment by alecristia** [comment]
It took me a while figure out how to fix this, so I'm writing down a complete response in case this is useful to someone in the future. 

Here's the solution:

- [metadata/datasets.yaml](https://github.com/langcog/metalab2/blob/master/metadata/datasets.yaml) has a "key" field, which for this dataset was 1sbeoPlEKxyjzlmWgzeSCVrumoS0wlMpX_Puv074r9lM which is wrong, so we'll look up information to replace that
- Visit the REAL spreadsheet you want to link up. In may case, it's https://docs.google.com/spreadsheets/d/1yCKAsu-vvQGemPga22F1cdtn90gs7Vp8UCto7HH10cE/edit#gid=818895612
- From that address, remove the stuff at the beginning up to the *d/*, and everything following the next */*. This leads to 1yCKAsu-vvQGemPga22F1cdtn90gs7Vp8UCto7HH10cE
- Copy-paste the resulting text into  [metadata/datasets.yaml](https://github.com/langcog/metalab2/blob/master/metadata/datasets.yaml) next to the appropriate key field
- Commit

Things not to do:

- I saw [scripts/cache_datasets.R](https://github.com/langcog/metalab2/blob/d1405a44ccd74d6220ac0769fb6e7074da69f88b/scripts/cache_datasets.R) combines this key field with the fixed text, like this: https://docs.google.com/spreadsheets/d/*$KEY*/export?id=*$KEY*&format=csv (NB key repeated) 
- I got lost for a while, because if one composes such an address my hand, and pastes it on a browser, one gets a 400 error. Not sure why this fails when I do it, but not when metalab does it, but whatever. 
- Don't look up the link to the csv for that spreadsheet that you want to link up. For instance, for my case, it was https://docs.google.com/spreadsheets/d/e/2PACX-1vQZFwVnJ7R-H-GSGYBeyeDM6LnakZN03efo6OCcGO7bLmaN8VviSurR0v5g2CbxaLYgOCXGAudt1k8P/pub?gid=1664900378&single=true&output=csv -- notice that neither the fixed text used by cache_datasets nor the key are found in the latter address
